### ISSUE TITLE
Sponsor design changes

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#1002]
We'll need to make changes to the Sponsor logo design to account for logos with light colors. 
![screen shot 2016-04-26 at 2 26 09 pm](https://cloud.githubusercontent.com/assets/1236811/14890842/f198b56c-0d18-11e6-8a14-7945f0092c67.png)

We hardcoded a specific logo image URL for campaign (#998, #1000) -- we'll want to remove that as well

**Comment by aaronschachter** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fJbl7Brd&#x2F;138-build-1-1-2-can-see-logo-because-of-white-background"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Build 1.1.2 Can see Logo because of white background</a>

**Comment by lkpttn** [comment]
![screen shot 2016-07-07 at 10 34 15 am](https://cloud.githubusercontent.com/assets/1865372/16670507/8d4ca0be-4468-11e6-8791-4dd8bc93fb6d.png)

Here's our updated design, side by side with the App Blue background

**Comment by tongxiang** [comment]
💯 ❤️
