### ISSUE TITLE
News API tweaks

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#1011]
Most items in this issue won't be resolved by code we commit into this repo, but adding as placeholder until we get our LDT News [Pantheon Wordpress into Github as a remote](https://pantheon.io/docs/guides/collaborative-development/#developing-in-sync).  Here's what needs to happen:

* [ ] Use `attachments.images.medium` property to populate `image_url` with a `https` (blocks #979) and to improve loading size by using a resized image. Currently we use the raw file that we upload, which is why we have weaksauce load times for some images
* [ ] Change Runscope tests to point to pantheonsite.io instead of pantheon.io -- currently failing because of 301's
* [ ] Change `DSOAPI` News URL to point to pantheonsite.io to avoid 301's

cc @lkpttn @sheyd

**Comment by lkpttn** [comment]
👍

**Comment by sheyd** [comment]
Anything DevOps side I can do to help here?

On Tue, May 10, 2016 at 9:24 AM, Luke Patton <notifications@github.com>
wrote:

> 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/DoSomething/LetsDoThis-iOS/issues/1011#issuecomment-218155908>
>



-- 
Sena Heydari
Director of Infrastructure Engineering, DoSomething.org
@alisinna

**Comment by aaronschachter** [comment]
I've created a clone of our Pantheon Wordpress project and closing this issue in favor of tracking the work in https://github.com/DoSomething/LetsDoThis-News/issues/1

@sheyd -- not within the scope of this issue, but it'd be helpful to chat about the QB of the general health checking / upgrades / maintenance of the Pantheon site, perhaps in #devops Slack!

**Comment by aaronschachter** [comment]
Opened #1012 to make the change to URL to avoid redirects
