### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#1013]
Sadness crash on `RCTImageView.m` line 178. Seems to always happen on the News Feed right away for users who are already authenticated -- haven't seen this happen yet. Curious if large loading times in https://github.com/DoSomething/LetsDoThis-News/issues/1 could be causing, but haven't dug in just yet.

Crash report: https://fabric.io/do-something/ios/apps/org.dosomething.letsdothis/issues/57191ca6ffcdc04250ec54c0

<img width="951" alt="screen shot 2016-05-10 at 9 19 51 pm" src="https://cloud.githubusercontent.com/assets/1236811/15167218/0689a55e-16f5-11e6-94e3-a647d7b3d7a9.png">

**Comment by aaronschachter** [comment]
I can replicate this crash!  Only when testing on iPhone 5 simulator though.

It will occur upon registering for a new account without an avatar, on iPhone 5, and then upon each subsequent app start.  Seems like that `RCTImageView` crash is always occurring when loading a non existent Avatar image.

So far the crashes (which have affected 551 users 😿 ) only occur on iPhone 5 and iPhone 4.

<img width="1033" alt="screen shot 2016-05-17 at 8 21 04 pm" src="https://cloud.githubusercontent.com/assets/1236811/15346442/1ba1bb70-1c6d-11e6-88ce-97034683d219.png">

cc @lkpttn

**Comment by lkpttn** [comment]
So weird. I wonder why it's not loading the default avatar like it does for the other devices.

**Comment by aaronschachter** [comment]
Still debugging, I believe the no avatar was a red herring: I'm testing by hardcoding an avatar URL for staging user 573bdf58a59dbfc6198b458c and still get the crash when testing on iPhone 5 / 9.3 simulator.

**Comment by aaronschachter** [comment]
Specifically seems to happen on iPhone 5 (not iPhone 5S or 6) in the `NetworkImage` component's [`onProgress` handler](https://github.com/DoSomething/LetsDoThis-iOS/blob/977177ece29bc9c40b4274a4310222ce5b9b6c28/ReactComponents/NetworkImage.js#L54). 

<img width="1158" alt="screen shot 2016-05-18 at 11 28 52 am" src="https://cloud.githubusercontent.com/assets/1236811/15370415/cc7e3a08-1ceb-11e6-97b9-a0e92421fde2.png">

````
     <Image
        source={this.props.source}
        style={this.props.style}
        onLoadStart={(e) => this.setState({loading: true})}
        onError={(e) => this.setState({error: e.nativeEvent.error, loading: false})}
        onProgress={(e) => this.setState({progress: Math.round(100 * e.nativeEvent.loaded / e.nativeEvent.total)})}
        onLoad={() => this.setState({loading: false, error: false})}>
        {content}
      </Image>;
````

Will comment out the progressHandler as a hotfix -- but still curious to find root of the bug to help diagnose other potential gotchas.  Side note that we're on React Native 0.22 -- now behind with latest 0.25
