### ISSUE TITLE
Add the download and action guide field information to the campaign template

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/LetsDoThis-iOS#1014]
Once this is exposed in the API, we'll want to pipe the info into the campaign page. The current solution is specced to be an embedded table with rows for each download and a row for the action guides, which display on a separate child view.

![screen shot 2016-05-11 at 10 26 54 am](https://cloud.githubusercontent.com/assets/1865372/15184426/211f3bf4-1763-11e6-8275-b82797df8ac5.png)

**Comment by aaronschachter** [comment]
Refs: 
- Downloads: https://github.com/DoSomething/phoenix/issues/6413
- Action Guides: https://github.com/DoSomething/phoenix/issues/6412

@lkpttn I'll be working on exposing Downloads via `UIWebView` per [this SO thread](http://stackoverflow.com/a/2832396/1470725)

**Comment by aaronschachter** [comment]
If we want to allow user to download files to device, we may likely need [additional code](http://stackoverflow.com/a/6238192/1470725)

**Comment by aaronschachter** [comment]
@lkpttn Here's a suggestion for how to track Google Analytics on this screens, based on [current screen names sent](https://github.com/DoSomething/product/wiki/Mobile-App#google-analytics):

* `campaigns/:id/attachment`
* `campaigns/:id/action-guides`

Any thoughts? Might want to run by #team-data as well. We could potentially track specific attachment ID if we expose the File id in the API -- refs https://github.com/DoSomething/phoenix/pull/6434#issuecomment-219565457

**Comment by lkpttn** [comment]
@aaronschachter 

Re: downloading files - offline/downloading not as important as submitting a build this week.

We can bring up the google analytics namespacing at the meeting on Wednesday, I think there's a couple other issues with GA worth discussing as well.

**Comment by aaronschachter** [comment]
We could potentially add a bottom toolbar with Share button so users could bookmark the PDF link. When the attachment is an image, there's an option to save image to device (but also potentially tweet out the attachment link, which we may want to avoid).
