### ISSUE TITLE
Cleanup Foundation and UIKit imports

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#429]
Refs code review in `DSOCampaign.h` -- https://github.com/DoSomething/LetsDoThis-iOS/commit/17207389b0bb286ea5f19b2a74f83a2b3002f91b

````
#warning We should add these imports to our .pch file
// And delete from each class
// Think they're still getting imported from somewhere though, as I tried commenting them out and everything still builds
// Possibly getting imported in our Pods files?
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
````

**Comment by tongxiang** [comment]
A [compelling critique of "over-relying on pre-compiled headers"](http://qualitycoding.org/precompiled-headers/). Less relevant to moving UIKit and Foundation into the pch, but perhaps relevant to the other headers we've kept there.

**Comment by tongxiang** [comment]
The most reasonable explanation of why the app runs even with missing Foundation and UIKit headers: 

Most CocoaPods import Foundation and UIKit, and when we import those CocoaPod header files, we're also importing Foundation and UIKit. (When a preprocessor finds an #import directive, it replaces that directive by the entire content of the specified header or file.) 

The [tools discussed in this SO post](http://stackoverflow.com/questions/1456966/how-to-detect-unused-methods-and-import-in-objective-c) may be able to help us verify which `#import`ed header files are actually unused. (In addition to methods!)
