### ISSUE TITLE
Research removal of @synthesize statements for _photo use

### ISSUE THREAD

**Issue by tongxiang** [DoSomething/LetsDoThis-iOS#468]
Within `DSOUser`, we use the `_photo` property within the `photo` property. Let's look into this to see if the `_photo` notation is necessary. 

References [this comment](https://github.com/DoSomething/LetsDoThis-iOS/pull/460#discussion_r41391016): 

> Minor, but this code is the only place we use the _photo notation (which is why we needed that @synthesize statement). Might be worth using self.photo to just keep th ecodebase consistent (but also probs worth reading up on which notation we should be using. synthesize used to be required when creating classes but things changed (before our time).. this might have just been because you were copying code from an older tutorial? Nothing needed for this branch but a cleanup issue worth looking into.

**Comment by aaronschachter** [comment]
Per 1st comment in http://stackoverflow.com/a/822646/1470725:
> with auto-synthesizing properties this is no longer necessary. Xcode synthesizes a @property xxxx with an ivar named _xxxx behind the scenes. Neat.

Using `self.photo` in the first place sounds like a `n00b` mistake i made when building out these classes, which might have been why you need it to work. Related to reading up on best practices in #645

**Comment by tongxiang** [comment]
@aaronschachter here's a [SO post](http://stackoverflow.com/questions/20848392/objective-c-not-creating-synthesized-variables) talking about the need for the @synthesize statement here:

>If you override both accessors (the setter and the getter) for an @property, the compiler assumes you don't need/want it to synthesize them -- and the corresponding instance variable -- for you. There are two possible solutions. Either declare the instance variable yourself...or use an explicit @synthesize statement. 

I've tried two ways to close this issue: either keep the @synthesize statement, since we've overriden the getter (`.photo`) and setter (`setPhoto`) properties; OR rename the getter and setter functions to `getAvatar` and `setAvatar`, which manipulate a separate `_photo` property. 

Thoughts on which option we should take? Or there may be a third option I'm unaware of?

**Comment by tongxiang** [comment]
[Here's](https://github.com/DoSomething/LetsDoThis-iOS/compare/onesolution?expand=1) how the second solution might look. 

I definitely prefer keeping the @synthesize statement.

**Comment by aaronschachter** [comment]
Yep, the `@synthesize` makes a lot to keep, I just wasn't sure when it's appropriate to use (lots of older blog posts about when it was first added [automatically in Xcode 4.4](http://useyourloaf.com/blog/property-synthesis-with-xcode-4-dot-4.html) and up). Thanks for looking into this, @tongxiang !
