### ISSUE TITLE
Reportback Item Gallery - Infinite scroll with Promoted then Approved

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#58]
For the Main Feed and Campaign Detail:

Display promoted photos first, in chronological order of their original submission date (not the approval date). 

After promoted photos, chronological approved reportbacks.

**Comment by lkpttn** [comment]
Display promoted photos first, in chronological order of their original submission date (not the approval date). After promoted photos, chronological approved reportbacks.

**Comment by aaronschachter** [comment]
Closing until this is required / ready
