### ISSUE TITLE
Props

### ISSUE THREAD

**Issue by marahml** [DoSomething/LetsDoThis-iOS#621]
UPDATED VERSION OF PROPS: We will start with just one prop (similar to a photo like). @lkpttn can you share designs for this?

- [ ]  Props button and bar available on reportback photos on the Campaign Detail gallery and in Reportback Item Detail screens

- [ ] Tapping on the Props button OR the photo results in a visual change to the photo to indicate that it's been given props

- [ ] Tapping on a Prop on the drawer submits a Prop to that photo through the Northstar API and increments the prop count

- [ ] Campaign Detail displays a props button with the same functionality

**Comment by aaronschachter** [comment]
Closing for now, not in scope for 1.1
