### ISSUE TITLE
Logged-in Email label needs constraints

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#654]
Long emails on smaller screens need some trailing constraint action:

![simulator screen shot nov 24 2015 6 20 47 pm](https://cloud.githubusercontent.com/assets/1236811/11387521/1b384af8-92e0-11e5-901e-11c4f2bb126b.png)

**Comment by aaronschachter** [comment]
@tongxiang This should be pretty straight forward, want to take this one on?

**Comment by tongxiang** [comment]
:+1:

**Comment by tongxiang** [comment]
@aaronschachter is this the desired behavior? Adding a single trailing constraint to the label produces the normal ellipses `...` action when there's a long email. 

Or do we want to produce multiple lines of text within the `uilabel`? 

![simulator screen shot dec 7 2015 10 34 37 am](https://cloud.githubusercontent.com/assets/5678066/11631057/4a1320f8-9cce-11e5-8f9d-1a71dd525e5b.png)

**Comment by tongxiang** [comment]
Alternatively, we can also choose [to shrink the text size.](http://stackoverflow.com/questions/7725795/getting-uilabel-to-produce-an-ellipsis-rather-then-shrinking-the-font)

**Comment by aaronschachter** [comment]
i was thinking ellipsis - let's go with that!
