### ISSUE TITLE
UX improvements for Emojii errors

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#667]
Uploading a reportback with an emojii in the caption seems to regularly fail. Would be nice to detect this before submitting to the API and display a better error message, if the API doesn't support emojii (we should confirm this before writing any code)

![no soup emojii for you](https://cloud.githubusercontent.com/assets/1236811/11453404/8ddf593a-95be-11e5-8f61-c9aae23601bf.jpeg)

**Comment by tongxiang** [comment]
Confirmed that we receive a 500 error when we submit Emojis within the reportback caption: 

`{"error":{"code":500,"message":"Could not create\/update reportback."}}`

**Comment by aaronschachter** [comment]
@tongxiang Adding checks to the fields in User Register form sounds good.

**Comment by aaronschachter** [comment]
Not an issue for this codebase, but the 500 error upon submitting an emoji feels more like it should be a 400 (in [which case we'd be displaying the "Could not create/update reportback" message](https://github.com/DoSomething/LetsDoThis-iOS/blob/f08dbd58b13a27a44795c32f4efc615b1095e0f7/Lets%20Do%20This/Categories/NSError%2BLDT.m#L49)). Ideally if we did any Northstar work on this, that message could be tweaked with a possible "Invalid characters" message.

 cc @jonuy

**Comment by tongxiang** [comment]
Closed by #681.

**Comment by aaronschachter** [comment]
Possibility of allowing :cat2: :tiger: 's for Reportbacks in https://github.com/DoSomething/phoenix/issues/6167
