### ISSUE TITLE
UX improvements for large Quantity errors

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#668]
Assuming this is a check on the API side (but let's confirm before writing any code). If there's a certain value that will fail, we can check for this before we submit to the API and display a more helpful error message than the usual: 

![slack for ios upload-7 png](https://cloud.githubusercontent.com/assets/1236811/11453413/d12f3ea8-95be-11e5-95c9-7b16f54f51f0.jpeg)

**Comment by tongxiang** [comment]
Thoughts on this, with help from @jonuy and @chloealee: 
1. There aren't any human-coded bounds to reportback numbers. 
2. There could be 32-bit / 64-bit integer overflow issues, either on a) the app b) the APIs (phoenix or northstar), or c) the database table.
