### ISSUE TITLE
UX improvement - alert user when Reportback caption is too long

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#682]
While the user is typing on the keyboard, the button is hidden. Upon dismissing the keyboard, there's no indication of why the user can't submit.

One easy way to do this would be to display an `LDTMessage` once the user has entered more than 60 characters -- and additionally don't allow the user to add any other characters past 60.

Another option could be to add a character counter, like on Twitter, which keeps track of how many characters the caption is.

Could also be worth increasing the height of the textbox to 2 lines? @lkpttn @marahml

Refs https://github.com/DoSomething/LetsDoThis-iOS/pull/395#issuecomment-142438872

**Comment by tongxiang** [comment]
Closed by #681.
