### ISSUE TITLE
prevent user from adding more chars to reportback after 60th

### ISSUE THREAD

**Issue by tongxiang** [DoSomething/LetsDoThis-iOS#690]
[References this comment](https://github.com/DoSomething/LetsDoThis-iOS/pull/681#issuecomment-162605633) on #681. 

We're currently telling the user that reportbacks over 60 characters aren't valid, and displaying an error message. Desired behavior is to prevent text field from updating with 61st character, and display warning message when they enter a 61st message.

**Comment by aaronschachter** [comment]
Without a live character counter, I think we still want to display the message once they enter a 61st character (although it wouldn't update in the text field).
