### ISSUE TITLE
Handle special characters in News Feed titles

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#753]
![screen shot 2016-01-19 at 8 41 20 am](https://cloud.githubusercontent.com/assets/1236811/12425460/b5a4d6ae-be89-11e5-9f8c-8f1721edbeaf.png)

**Comment by aaronschachter** [comment]
This feels more like a weird bug in the WP API that `title` and `title_plain` are [exactly the same](http://dev-ltd-news.pantheon.io/?json=get_post&post_id=109):
![screen shot 2016-01-21 at 5 48 47 pm](https://cloud.githubusercontent.com/assets/1236811/12500378/865f892c-c067-11e5-9869-c306821fd5b5.png)

I'm not having much luck figuring out if there's a way to change this in the WP JSON API plugin.

Doesn't seem like React Native doesn't have a [`dangerouslySetInnerHTML`](https://facebook.github.io/react/tips/dangerously-set-inner-html.html) method like they do in React: http://stackoverflow.com/questions/29334984/render-html-in-react-native

cc @jonuy

**Comment by aaronschachter** [comment]
New answer of yesterday: http://stackoverflow.com/a/35025236/1470725, which contains sample code

> React Native has updated the WebView component to allow for direct html rendering

**Comment by aaronschachter** [comment]
WebView doesn't work well as we want the height to be dynamic (and need the webview to have its own stylesheet, gross)

**Comment by jonuy** [comment]
We could create a helper method that parses strings and finds those that match those special char values and essentially pass it through something like...
```
// Seems like it's base-10
String.fromCharCode(parseInt(<unicode value here>, 10))
```

So for example, finding a `&#8217` in a string gets passed into this function: `String.fromCharCode(parseInt(8217,10))` which (unless JavaScriptCore doesn't work like V8) should return `’`.
