### ISSUE TITLE
Display News Feed photo credits

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#754]
Info button should toggle visibility:
![news feed card](https://cloud.githubusercontent.com/assets/1236811/12425499/eb3b8f9c-be89-11e5-9f28-d3d16e6d1a59.png)

**Comment by lkpttn** [comment]
@aaronschachter The photo credit shouldn't be too long, but we should be prepared for something that spans multiple lines, so the height of that view should be variable.
