### ISSUE TITLE
Cause colors

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/LetsDoThis-iOS#756]
Here's the list of all campaign causes and their corresponding hex codes.

Cause | Hex Code
------------ | -------------
Animals | #1BC2DD
Bullying | #E75526
Disasters | #1D78FB
Discrimination | #E1000D
Education | #1AE3C6
Environment | #12D168
Health | #BA2CC7
Homelessness | #FBB71D
Sex | #FB1DA9
Violence | #F1921A
Poverty | #69D24B
Relationships | #A01DFB

**Comment by aaronschachter** [comment]
@lkpttn Health is split into two distinct causes: Physical Health and Mental Health. Using the same color for both now, but we'll likely want to change this as they appear next to each other alphabetically.

**Comment by aaronschachter** [comment]
@lkpttn Hex colors in the iOS app now load hex values from the Categories in the LDT News app.
