### ISSUE TITLE
Update assets

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#804]
* [x] Tab Bar icons
* [x] Onboarding images
* [x] Default Avatar
* [x] App icon
* [x] Login/Register background pattern

**Comment by aaronschachter** [comment]
@lkpttn Using App Export 0.92, I believe the white lines/square inside the News Tab Icon need to be transparent, not white:
![screen shot 2016-02-15 at 10 22 19 pm](https://cloud.githubusercontent.com/assets/1236811/13066324/d07e26c4-d432-11e5-873c-341c14608326.png)

**Comment by aaronschachter** [comment]
@lkpttn The App Icon assets also don't appear to be sized correctly when I drag and drop them into our Images.xcassets.

Do you mind taking on these asset issues? I'm happy to help if you have any questions -- but it would help get these in quicker.

![screen shot 2016-02-15 at 10 36 12 pm](https://cloud.githubusercontent.com/assets/1236811/13066510/b5d9ccc2-d434-11e5-884a-7c023fe66f5c.png)

**Comment by lkpttn** [comment]
Yeah, these are one of my top priorities for today.
