### ISSUE TITLE
Filter SMS Game campaigns

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#813]
Need to inspect a campaign's type property to only display Campaigns with type `campaign`

cc @jonuy

**Comment by aaronschachter** [comment]
It appears the Phoenix `GET campaigns` index endpoint [filters out SMS games by default](https://github.com/DoSomething/phoenix/blob/e17d966117e37e2629dea39a6627ef62a359d064/lib/modules/dosomething/dosomething_campaign/includes/CampaignTransformer.php#L115).

On Thor, Little Rock Nine Text (campaign id 6163) is an active sms game, tagged with discrimination (term id 14): https://thor.dosomething.org/us/node/6163
However its nowhere to be found in https://thor.dosomething.org/api/v1/campaigns?term_ids=14&count=50

I found this by changing the staging Pregnancy Text (id 51) campaign from `campaign` to `sms_game` -- the campaign was no longer returned by the campaign index.

cc @jonuy @weerd

**Comment by jonuy** [comment]
Ah. Look at that. I was sorta wondering why I never saw an `sms_game` come through.

**Comment by aaronschachter** [comment]
A few days later and I don't think that's the correct place its getting set though (so it's still kind of a mystery). I suspect that [line](https://github.com/DoSomething/phoenix/blob/e17d966117e37e2629dea39a6627ef62a359d064/lib/modules/dosomething/dosomething_campaign/includes/CampaignTransformer.php#L115) is filtering by the `node.type`., not the campaign's `field_campaign_type` value. cc @weerd
