### ISSUE TITLE
NavigationBar styles

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#819]
Updated: Use opaque white navigationBar for Campaign, User View Controllers, and no longer hide navigationBar upon swipe

Original issue: 
UserViewController navigationBar not always transparent. Loading a VC with a ReactView sometimes renders the navigationBar as opaque even though we set to translucent.

**Comment by lkpttn** [comment]
Repurposing this issue, we're going to add opaque navigatonBars on almost all the views just to cut down on complexity of hiding and showing, etc. Mostly affects the Hub, Campaign Detail and Cause Detail pages.

![hub signups](https://cloud.githubusercontent.com/assets/1865372/12985147/1099add6-d0bf-11e5-8832-bdc7e942388e.png)
![campaign detail](https://cloud.githubusercontent.com/assets/1865372/12985154/165c2e1a-d0bf-11e5-8da5-3ee7261192eb.png)
![cause individual](https://cloud.githubusercontent.com/assets/1865372/12985161/1dcb7fa2-d0bf-11e5-8908-05ef5f5f06a7.png)
