### ISSUE TITLE
Update banner color for notifications

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/LetsDoThis-iOS#825]
Let's use the App blue, #352FB0 for confirmation and keep the red for errors.

**Comment by aaronschachter** [comment]
@lkpttn This may look odd now that our status bar text is black and not white. Would a lighter blue from the pallete ( #756 ) be better?

**Comment by aaronschachter** [comment]
@lkpttn Assigning this one to you. You can test by changing the colors in the [LDTMessageDefaultDesign.json](https://github.com/DoSomething/LetsDoThis-iOS/blob/develop/Lets%20Do%20This/Views/LDTMessageDefaultDesign.json)

**Comment by aaronschachter** [comment]
Closed by #842
