### ISSUE TITLE
Replace "Prove It" button with disclosure arrow and link to campaign page

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/LetsDoThis-iOS#840]
Due to limited space on iPhone 5 and below, we need to rethink the "Prove It" button directly on the hub that shows in each cell. At smaller widths it becomes untenable.

Our current solution is to have the entire cell link back to the campaign detail page and signify this with the disclosure arrow. This means that you can no longer reportback from the hub, but you get much better tap targets and information in each hub cell.

The width of the text box in each cell should be 16pts from the left margin and 16pts from the disclosure arrow.

![screen shot 2016-02-17 at 10 42 11 am](https://cloud.githubusercontent.com/assets/1865372/13114813/205c69d6-d563-11e5-90b1-832031a8db04.png)

**Comment by aaronschachter** [comment]
Duplicate of #659
