### ISSUE TITLE
App fails to build in Simulator when using js.bundle

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#920]
Not a blocker, as it works when we build to a physical device (and can then archive) -- but something worth cleaning up. Refs https://github.com/facebook/react-native/issues/5770

> 2016-03-07 09:22:08.433 DoSomething[1436:91544] *** Terminating app due to uncaught exception 'RCTFatalException: Unable to execute JS call: __fbBatchedBridge is undefined', reason: 'Unable to execute JS call: __fbBatchedBridge is undefined'

**Comment by kxxoling** [comment]
＋1, this is found when I comment the line ``jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];`` and use ``jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];`` instead.

**Comment by kxxoling** [comment]
Debug mode works fine on real machine, seems it was something wrong with production specific settings.

**Comment by aaronschachter** [comment]
Upgrading to RN 0.22, I get this error when running on my Debug scheme but not on Release. I'm curious if this relates to my package.json looking like [this](https://github.com/facebook/react-native/issues/6597#issuecomment-204565032):
````
 "bin": {
    "react-native": "local-cli/wrong-react-native.js"
  },`
````
Ability to run bundle from Simulator on Release feels like reason enough to close this to clear out some of these minor issues.
