### ISSUE TITLE
Bug in signing up for 2nd run when you've already completed campaign in its 1st run

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#956]
This looks like an API bug --  but need to more testing to confirm.  Suspect this happens when you've reported back for a campaign's first run and signup for it's 2nd:

Logged with my DS account, phoenix user 1176550
Noticed Birthday Mail (campaign id 2461) reportback in my profile under "Actions I've Done"
Tapped on Birthday Mail: was presented with a Do This Now button on Campaign view
Signed up, and got a confirmation message.

My old reportback appears in Campaign View, and my profile looks the same (was expecting to see Birthday Mail in the Doing It now section).

API suggests the 2nd signup was never created (even though I got the confirmation back), there's only 1 result for my user: https://www.dosomething.org/api/v1/signups?user=1176550&campaigns=2461
it has a created date of 1406644593 (July 2014)... but the `campaign_run` is set to 6454, which is Birthday Mail's 2nd run:

![screen shot 2016-03-12 at 9 55 34 am](https://cloud.githubusercontent.com/assets/1236811/13724385/b8c3d0a0-e838-11e5-80f3-4c8f283eb0a4.png)
which has a start date of June 2015
![screen shot 2016-03-12 at 9 59 48 am](https://cloud.githubusercontent.com/assets/1236811/13724397/2f85d012-e839-11e5-9c28-8f2d564a06c2.png)

Signup confirmation screenshot below (3/12/2016). Birthday Mail now shows as a completed campaign with my old reportback for me upon viewing it (as the signup exists for the current run)
![img_0349 png](https://cloud.githubusercontent.com/assets/1236811/13724431/30f4abfc-e83a-11e5-94d4-de2510f49db4.jpeg)

cc @jonuy @angaither

**Comment by aaronschachter** [comment]
Testing https://github.com/DoSomething/phoenix/pull/6278 on Thor, @angaither updated my corrupt production Birthday Mail signup data to re-test this.  The "you" in this issue description happened to particularly be my user account testing on my 2nd signup for campaign 2461 (Birthday Mail)

*Short story*: It looks good! Signup worked for me.

*Long story*:
Revisited my profile with updated data before reporting back for Run 2. Saw Birthday Mail in my reportbacks, here's the API response:
![screen shot 2016-03-15 at 8 12 58 pm](https://cloud.githubusercontent.com/assets/1236811/13801150/78374768-eaec-11e5-9150-2e1790ea3e88.png)

Posted signup, things are as exepcted: I see Birthday Mail in my Doing section, and also my completed Birthday Mail reportback in the Done section. Tapping through the Birthday Mail in my Done shows me as still needing to Prove it.

What's odd here is that the `meta.pagination.total` is incorrect, it says 1 when it should be 2:

![screen shot 2016-03-15 at 8 32 11 pm](https://cloud.githubusercontent.com/assets/1236811/13801226/322e8762-eaed-11e5-841e-fadbdef02793.png)

The final step might be to reportback on this new signup, but the count mismatch looks like a newly discovered bug. @chloealee -- how do we calculate that count? Is this something we missed to fully resolve https://github.com/DoSomething/phoenix/issues/6266 ?

Going to close this issue out -- since we now see 2 signups as expected.

**Comment by chloealee** [comment]
@aaronschachter we use [this function](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L841) which does go through the query but just double checked the code and it seems to look right. 

This is so strange! When hitting https://thor.dosomething.org/api/v1/signups?user=1176550, the total is correct and accounts for both Birthday Mail signups.

**Comment by chloealee** [comment]
Also, when hitting https://thor.dosomething.org/api/v1/signups?user=1176550&campaigns=362, the total is correct, showing signups for the same campaign but on different runs (same situation [as buggy link above](https://thor.dosomething.org/api/v1/signups?user=1176550&campaigns=2461) but with a different campaign). 

Is there something about the Birthday Mail campaign that might be triggering this?

**Comment by chloealee** [comment]
@aaronschachter just checked your link again and looks like it's working now! Not sure what caused it but glad to see that it is working as expected now. Closing the loop :)

**Comment by aaronschachter** [comment]
Weird ... but hey at least it's working!  Thanks @chloealee

**Comment by aaronschachter** [comment]
@chloealee Are these `pagination` values cached?  Tom was testing mobile app by signing up for 200 campaigns. When I ping for his signups in browser, it shows a total of 3, when there are definitely more.  

My response for https://northstar.dosomething.org/v1/signups?user=56eab76e469c6444628b60f2 below. He was testing signups earlier this morning:

![screen shot 2016-03-22 at 8 27 39 am](https://cloud.githubusercontent.com/assets/1236811/13957022/2cf1575a-f008-11e5-9469-f362672a6393.png)

**Comment by chloealee** [comment]
@aaronschachter looks like these are cached: https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L1083. Does this need to be changed? cc @weerd

**Comment by aaronschachter** [comment]
I'm looking specifically at the Signups endpoint's pagination (that looks like its calculating pagination for Reportbacks). For signups, I *think* we'd need the live count every time when determining user's campaign activity / profile.. but maybe good to chat through how caching should/work specifically for Signups..

**Comment by weerd** [comment]
@chloealee yep! Defs needed. Checkout the commit for further info: https://github.com/DoSomething/phoenix/commit/325abffb7f7f185e300334bca4d41b293037cac1
:smile:

**Comment by chloealee** [comment]
ah sorry - sent the wrong link! But yes, it does look like it's cached. https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L849-L859 

Should I remove this so it makes the request each time? Or, I can also maybe set the cache time to a smaller time frame? @aaronschachter @weerd

**Comment by aaronschachter** [comment]
I'll create a new issue in the Phoenix repo to describe the problem and we can spec it out there @chloealee @weerd

**Comment by chloealee** [comment]
Cool, thanks @aaronschachter !
