### ISSUE TITLE
Update the Notifications copy on the Settings page

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/LetsDoThis-iOS#959]
We'll remove the toggle and just present the copy until we have actual different types of notifications to toggle on and off. 

![settings](https://cloud.githubusercontent.com/assets/1865372/13783271/1b8e06fa-eaa1-11e5-9dd1-9a1d8ca9e45f.png)

**Comment by aaronschachter** [comment]
While we're tweaking some of these Settings, if you go into Settings > DoSomething > Location this is the copy that indicates why we want your location:
`We need your location to give you the most relevant campaigns!`

Are we ok with this for launch? It's a quick copy change we can make while we're working on our release candidate

@lkpttn @marahml

**Comment by marahml** [comment]
Hmm I see Luke snuck back that line again that we've already removed. @aaronschachter please remove "We'll never interrupt you to ask you for ratings." and keep everything else the same

**Comment by marahml** [comment]
Change ---> We need your location to give you the most relevant campaigns! to "We'll use your location to keep making your experience better over time!"
