### ISSUE TITLE
News Article View Controller tweaks

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#974]
Per our app review:

> For example, before accessing the news articles;
- include links to third-party news articles that launch in a web browser outside of the application
or
- require the user to configure third-party RSS feeds/sources.

Looking into what we get out of `WKWebView` to support iOS8, or potentially switching over to `SFSafariViewController` and only supporting iOS9.

**Comment by lkpttn** [comment]
Let's also change "View Full Article" to "View Original Story" so we're not sounding possessive of the linked content.

**Comment by lkpttn** [comment]
On the advice of Matt Holford, let's change the link to just launch safari directly. It's the easiest solution which is a direct interpretation of what we heard from App Review. 

Want to make sure that we're doing the new deep link app thingy that iOS 9 supports though between apps.

**Comment by aaronschachter** [comment]
Closed by #975
