### ISSUE TITLE
Add terms and conditions/privacy policy to the settings screen

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/LetsDoThis-iOS#982]
LETS GET EXPLICIT. The easiest solution would be to launch safari, but if we can wrap it in a web view easily, lets do that.

![settings](https://cloud.githubusercontent.com/assets/1865372/14051166/367982d4-f297-11e5-8e35-478a6d67d701.png)

**Comment by lkpttn** [comment]
We're going to remove the disclosure arrow since these aren't parent rows of another view but rather move you outside the app.

**Comment by aaronschachter** [comment]
Closed by #983
