### ISSUE TITLE
Add DoSomething.org into our App Store description

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#987]
If you search on app store for dosomething.org, we don't show up, because there's no mention of dosomething.org anywhere in the description (our seller name is listed as Do Something, Inc per our DNB number).

This won't be handled through code, but is a task for when we submit our next release. cc @lkpttn

**Comment by lkpttn** [comment]
I added it into the description for now, but I'm going to leave the issue open to remind us to change the keywords in the next version.

**Comment by aaronschachter** [comment]
@lkpttn Should we close this out -- did you add as keyword?

**Comment by lkpttn** [comment]
Done and done
