### ISSUE TITLE
Add sponsor image

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#991]
1st designs from @lkpttn via Slack #ios

![screen shot 2016-04-25 at 11 21 16 am](https://cloud.githubusercontent.com/assets/1236811/14792213/1a209a38-0ace-11e6-846a-944b71c97832.png)

cc @jonuy

**Comment by lkpttn** [comment]
The limiting variable of the logo image is the height. 55px tall, with a variable width.

**Comment by aaronschachter** [comment]
@lkpttn We can hardcode this to just display one sponsor for now, but per #mobile-app Slack discussion around this today -- it sounds like we'll want to eventually support more than 1...

**Comment by aaronschachter** [comment]
Fighting with Flexbox to right-align the logo image without specifying a hardcoded width. Will spend a bit more time digging -- worst case could be to display the "Powered by" label above the image, based on https://github.com/facebook/react-native/issues/950#issuecomment-94850633

![screen shot 2016-04-26 at 11 25 42 am](https://cloud.githubusercontent.com/assets/1236811/14829808/46425532-0ba2-11e6-9698-5c20213b7fd8.png)

![screen shot 2016-04-26 at 11 29 04 am](https://cloud.githubusercontent.com/assets/1236811/14829815/4e581842-0ba2-11e6-8542-93fe73f8e4ee.png)
