### ISSUE TITLE
Hardcode the Newscorp logo for launch

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/LetsDoThis-iOS#998]
![news_corp_logo](https://cloud.githubusercontent.com/assets/1865372/14862313/c98f69a2-0c7e-11e6-9e3d-1898bd0e9c8f.png)

Attaches to campaign "One for the Books" in Education.

The phoenix version of this logo is white and problematic with our current background style. We'll revisit this post-launch but for now we just gotta get something in that works.

**Comment by aaronschachter** [comment]
Closed by #1000
